---
# This playbook is used to locate VMs inside a vSphere datacenter, on which
# then actions can be run.
- name: 'Locate VM in vSphere'
  community.vmware.vmware_guest_find:
    hostname: "{{ vsphere_host }}"
    username: "{{ vsphere_username }}"
    password: "{{ vsphere_password }}"
    validate_certs: "{{ vsphere_validate_certs }}"
    name: "{{ inventory_hostname }}"
  register: 'vm_location'
  delegate_to: "{{ vsphere_api_host }}"
