---
- name: 'Create inventory'
  hosts: 'all'
  tasks:
    - name: 'Add new host'
      ansible.builtin.add_host:
        name: "molecule-{{ ansible_facts['hostname'] }}"
        group: 'vmware'
        vsphere_api_host: "{{ ansible_facts['hostname'] }}"
        vsphere_host: 'vcenter.lab'
        vsphere_validate_certs: false
        vsphere_username: 'administrator@vsphere.local'
        vsphere_password: 'Password1@'
        vsphere_datacenter: 'Datacenter'
      changed_when: false

- name: 'Converge'
  hosts: 'vmware'
  gather_facts: false
  tasks:
    - name: 'Create VM'  # noqa var-naming[no-role-prefix]
      ansible.builtin.import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        vmware_target_action: 'provision_guest'
        vmware_target_state: 'present'
        vmware_target_esxi_hostname: 'esxi.lab'
        vmware_target_disks:
          - size_gb: 1
            type: 'thin'
            datastore: "{{ default_datastore }}"
    - name: 'Snap VM'  # noqa var-naming[no-role-prefix]
      ansible.builtin.import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        vmware_target_action: 'snap'
        vmware_target_state: 'present'
    - name: 'Delete VM'  # noqa var-naming[no-role-prefix]
      ansible.builtin.import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        vmware_target_action: 'provision_guest'
        vmware_target_state: 'absent'
        vmware_target_esxi_hostname: 'esxi.lab'
