---
dependency:
  name: 'galaxy'
driver:
  name: ${DRIVER_NAME:-docker}
platforms:
  - name: "vmware-${MOLECULE_DISTRO:-debian9}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian9}-ansible:latest"
    command: '/lib/systemd/systemd'
    pre_build_image: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    privileged: true
provisioner:
  name: 'ansible'
verifier:
  name: 'ansible'
