---
# This playbook will remove all snapshots for all VMs in the inventory
- name: 'Ensure snapshots of targeted VMs'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Ensure snapshots'
      ansible.builtin.import_role:
        name: 'vmware'
      vars:
        vmware_target_action: 'snap'
        vmware_target_state: 'remove_all'
