---
# This playbook will take vm1 and copy it to a new template (this name must
# also be in the inventory!)
- hosts: 'deb10-base'
  gather_facts: false
  tasks:
    - import_role:
        name: 'vmware'
      vars:
        target_action: 'provision_guest'
        target_state: 'present'
        target_esxi_hostname: 'esxi.example.com'
        target_template: 'vm1'
        target_is_template: 'True'
      run_once: true
